# Generated by Django 3.0 on 2019-12-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20191211_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timezone',
            field=models.CharField(max_length=100),
        ),
    ]
