# Generated by Django 3.0 on 2019-12-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20191211_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sessions',
        ),
        migrations.AddField(
            model_name='event',
            name='sessions',
            field=models.ManyToManyField(blank=True, null=True, to='event.Session'),
        ),
    ]
