# Generated by Django 3.0 on 2019-12-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20191212_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='speaker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
